// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ORTInternationalHotel.Web.Data;

#nullable disable

namespace ORTInternationalHotel.Web.Migrations
{
    [DbContext(typeof(ORTInternationalHotelContext))]
    partial class ORTInternationalHotelContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ORTInternationalHotel.Web.Models.Habitacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacidad")
                        .HasColumnType("int");

                    b.Property<int>("HotelId")
                        .HasColumnType("int");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal>("PrecioPorNoche")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HotelId");

                    b.ToTable("Habitaciones");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacidad = 2,
                            HotelId = 1,
                            Numero = "101",
                            PrecioPorNoche = 120.00m,
                            Tipo = 1
                        },
                        new
                        {
                            Id = 2,
                            Capacidad = 4,
                            HotelId = 1,
                            Numero = "102",
                            PrecioPorNoche = 260.00m,
                            Tipo = 2
                        },
                        new
                        {
                            Id = 3,
                            Capacidad = 1,
                            HotelId = 2,
                            Numero = "201",
                            PrecioPorNoche = 90.00m,
                            Tipo = 0
                        },
                        new
                        {
                            Id = 4,
                            Capacidad = 3,
                            HotelId = 2,
                            Numero = "202",
                            PrecioPorNoche = 340.00m,
                            Tipo = 2
                        },
                        new
                        {
                            Id = 5,
                            Capacidad = 5,
                            HotelId = 3,
                            Numero = "301",
                            PrecioPorNoche = 210.00m,
                            Tipo = 3
                        });
                });

            modelBuilder.Entity("ORTInternationalHotel.Web.Models.Hotel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CantidadEstrellas")
                        .HasColumnType("int");

                    b.Property<string>("Ciudad")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Direccion")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.ToTable("Hoteles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CantidadEstrellas = 5,
                            Ciudad = "Buenos Aires",
                            Direccion = "Av. Libertador 1234",
                            Nombre = "ORT International Hotel - Buenos Aires",
                            Pais = "Argentina"
                        },
                        new
                        {
                            Id = 2,
                            CantidadEstrellas = 5,
                            Ciudad = "Nassau",
                            Direccion = "Ocean Drive 500",
                            Nombre = "ORT International Hotel - Bahamas",
                            Pais = "Bahamas"
                        },
                        new
                        {
                            Id = 3,
                            CantidadEstrellas = 4,
                            Ciudad = "Madrid",
                            Direccion = "Gran Vía 88",
                            Nombre = "ORT International Hotel - Madrid",
                            Pais = "España"
                        });
                });

            modelBuilder.Entity("ORTInternationalHotel.Web.Models.Pasajero", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("PaisOrigen")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Pasajeros");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Apellido = "Auday",
                            Documento = "30111222",
                            Email = "karina.auday@ort.edu.ar",
                            Nombre = "Karina",
                            PaisOrigen = "Argentina",
                            Telefono = "+54 11 4000-1111"
                        },
                        new
                        {
                            Id = 2,
                            Apellido = "Smith",
                            Documento = "US4455667",
                            Email = "john.smith@example.com",
                            Nombre = "John",
                            PaisOrigen = "Estados Unidos",
                            Telefono = "+1 305-555-0110"
                        },
                        new
                        {
                            Id = 3,
                            Apellido = "Fernández",
                            Documento = "28999111",
                            Email = "lucia.fernandez@example.com",
                            Nombre = "Lucía",
                            PaisOrigen = "Argentina",
                            Telefono = "+54 11 4000-2222"
                        });
                });

            modelBuilder.Entity("ORTInternationalHotel.Web.Models.Reserva", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaDesde")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaHasta")
                        .HasColumnType("datetime2");

                    b.Property<int>("HabitacionId")
                        .HasColumnType("int");

                    b.Property<int>("HotelId")
                        .HasColumnType("int");

                    b.Property<decimal>("MontoTotal")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("PasajeroId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HabitacionId");

                    b.HasIndex("HotelId");

                    b.HasIndex("PasajeroId");

                    b.ToTable("Reservas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Estado = 1,
                            FechaDesde = new DateTime(2026, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaHasta = new DateTime(2026, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HabitacionId = 1,
                            HotelId = 1,
                            MontoTotal = 600.00m,
                            PasajeroId = 1
                        },
                        new
                        {
                            Id = 2,
                            Estado = 0,
                            FechaDesde = new DateTime(2026, 12, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaHasta = new DateTime(2026, 12, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HabitacionId = 3,
                            HotelId = 2,
                            MontoTotal = 630.00m,
                            PasajeroId = 1
                        },
                        new
                        {
                            Id = 3,
                            Estado = 1,
                            FechaDesde = new DateTime(2026, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaHasta = new DateTime(2026, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HabitacionId = 4,
                            HotelId = 2,
                            MontoTotal = 1360.00m,
                            PasajeroId = 2
                        },
                        new
                        {
                            Id = 4,
                            Estado = 0,
                            FechaDesde = new DateTime(2027, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaHasta = new DateTime(2027, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HabitacionId = 5,
                            HotelId = 3,
                            MontoTotal = 1050.00m,
                            PasajeroId = 3
                        });
                });

            modelBuilder.Entity("ORTInternationalHotel.Web.Models.Habitacion", b =>
                {
                    b.HasOne("ORTInternationalHotel.Web.Models.Hotel", "Hotel")
                        .WithMany("Habitaciones")
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hotel");
                });

            modelBuilder.Entity("ORTInternationalHotel.Web.Models.Reserva", b =>
                {
                    b.HasOne("ORTInternationalHotel.Web.Models.Habitacion", "Habitacion")
                        .WithMany("Reservas")
                        .HasForeignKey("HabitacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ORTInternationalHotel.Web.Models.Hotel", "Hotel")
                        .WithMany("Reservas")
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ORTInternationalHotel.Web.Models.Pasajero", "Pasajero")
                        .WithMany("Reservas")
                        .HasForeignKey("PasajeroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Habitacion");

                    b.Navigation("Hotel");

                    b.Navigation("Pasajero");
                });

            modelBuilder.Entity("ORTInternationalHotel.Web.Models.Habitacion", b =>
                {
                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("ORTInternationalHotel.Web.Models.Hotel", b =>
                {
                    b.Navigation("Habitaciones");

                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("ORTInternationalHotel.Web.Models.Pasajero", b =>
                {
                    b.Navigation("Reservas");
                });
#pragma warning restore 612, 618
        }
    }
}
